### ISSUE TITLE
Types for variables

### ISSUE THREAD

**Issue by lks9** [lks9/angr#10]
**Description**

Extract the types from the DWARF information.

We already have these kinds of types just relate to them?

`state.mem[addr].int32`

** Update**
Mostly done! We can get the type of a (dwarf) variable and its address. But it is still open to relate the cle types with the angr memory types.
```
# returns 'unsigend int'
state.nvariables["i"].type.name
# returns the value
state.mem[state.nvariables["i"].addr].uint
```
But `'char'` is not `char` (the second is not a string) and `'unsigned int'` is not `uint`!

**Comment by ducorduck** [comment]
@lks9 we already have class `cle.backend.elf.variable_type.VariableType` which store name as well as byte_size of the variable type. Do we have to use it to resolve it to one of the type that can be resolve using `state.mem[addr].type`? Or am i missing something?

**Comment by lks9** [comment]
Yes, we could do it this way. However, I would expect <strike>two</strike> *three* problems that need to be solved:

* The class `cle.backend.elf.variable_type.VariableType` currently has only name and byte size. But C has a lot more complex types like pointers of a certain type, structures with typed members, arrays etc. These are all not supported yet as it seems.
* The mapping to angr's `state.mem[addr].TYPE` is certainly not trivial. *EDIT:* For any types where the mapping can't be inferred, it should be sufficient to print out the bytes instead.
* *EDIT:* Also, name and byte size are not sufficient for the basic types. There is also signedness and endianess. The latter is not so important, since we are only working on x86_64. But the former makes the difference between `unsigned int` and `int`.

**Comment by lks9** [comment]
Ok, with 12644e317e05b5f42898eddba7f1e47391048918 it is now possible to use:
```
state.nvariables["i"].mem
```
And this `.mem` has an angr type which can be manipulated. For base type the relation between dwarf and angr types works by looking up the name in angr's `ALL_TYPES`. For other types we create a placeholder `SimRegType` with the correct size.

This should solve the remaining thing.
