### ISSUE TITLE
resolve void pointer

### ISSUE THREAD

**Issue by ducorduck** [lks9/angr#19]
### Description

the member `void *struct_pointer` of `struct various_type` is resolved with a wrong result by `.member("struct_pointer").mem.concrete`

Example can be found in `test_dwarf_variable.py`  in method `test_resolve_local_struct`

**Comment by ducorduck** [comment]
i thought it was solved when i pull the changes from cle but the test for local_struct still fail

**Comment by lks9** [comment]
The problem was that we have a different expected result for `struct_pointer` of `local_struct`, see the binary. I fixed the test in 210cb5a4c.
