### ISSUE TITLE
Binary examples for the variable locations

### ISSUE THREAD

**Issue by lks9** [lks9/angr#3]
**Descritption**
Binaries for various locations of global and local variables (for future test cases). Static vars, global vars, variables inside the main function body, inside a loop, inside a switch statement, inside a block...

**Estimated time**
5

**Comment by lks9** [comment]
@ducorduck I have just pushed some binary "various_variables" into https://github.com/lks9/binaries, see https://github.com/lks9/binaries/commit/b6ec5d2bea12066e6ec9762415195ffc8ff71cc6. You can find it in `angr-dev/binaries/tests/various_variables`. I think this might be a good starting point to extend and/or do the other stories in parallel.

**Edit:** Sorry, I was a bit incorrect the binary is under `angr-dev/binaries/x86_64/various_variables`.

**Comment by ducorduck** [comment]
@lks9 it seems like i can't pull the changes from [lks9/binaries](https://github.com/lks9/binaries) because i don't have the permission. Can you add me in?
