### ISSUE TITLE
Resolve variables in a state

### ISSUE THREAD

**Issue by lks9** [lks9/angr#5]
**Descritption**
In some angr state, resolve the variable from a name.

```
var = state.nvariables["x"]
var.addr
var.name
var.global
var.local
```
EDIT: we don't need `.global` and `.local`, not implemented (yet).

Or use the class variables we already have in angr...

**Depends on**
#3 
#9 

**Estimated time**

**Comment by lks9** [comment]
Because `.addr` is dependent of the state, we should return an `cle.backends.elf.variable.Variable` which is stateless.

**Comment by lks9** [comment]
Ok, I added #13 to solve the `.addr` issue above. But I still couldn't implement it because  #11 is still open.

@ducorduck Could you give #11 a try? The computation of the `.addr` should happen in `cle.backends.elf.variable`. I think a method with a `pc` argument should suffice.

At a second step, one could simply call the new method in `cle.backends.elf.variable` from the `.addr` in the wrapper object `angr.state_plugins.nvariables.SimVariable`.

Thanks!

**Comment by ducorduck** [comment]
> @ducorduck Could you give #11 a try? The computation of the `.addr` should happen in `cle.backends.elf.variable`. I think a method with a `pc` argument should suffice.

we can't compute the cfa using only the pc, right? we would need some other register (in our case rbp or rsp) to calculate it. So how about a method like `addr_from_state`?

**Comment by lks9** [comment]
Yes that would be great!
