### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by lks9** [lks9/angr#7]
**Description**

Test cases for the binaries.

**Depends on**
#3 , #5

**Comment by lks9** [comment]
Thank you for the test class file. I just renamed it for simplicity:

[tests/test_dwarf_variables.py](https://github.com/lks9/angr/blob/master/tests/test_dwarf_variables.py)

This includes the tests for local and global variables. Please, if you have any other tests, could you add them here? And then close this issue. Thanks!

**Comment by lks9** [comment]
PS: I also added string treatment, see adc2475aee89525d93aefdeb4635140736a1627f.

**Comment by ducorduck** [comment]
I've updated it all, with f3170d1
